# Modelos Multiplos Preditivos - Cap. 8
## 0 - Bibliotecas importadas

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

## 1 - Carregando dataset 'Wine Quality'
* Dados numéricos;
* Não houve necessidade de fazer tratamento quanto a falta ou inconsistência nos dados;
* 11 características e target sendo sobre a qualidade do vinho (0-qualidade ruim- até 10-Excelente qualidade-);
* Não está balanceado (há mais vinhos normais do que excelentes ou ruins);

### Vinho Branco

In [2]:
df_white = pd.read_csv('./winequality-white.csv', sep = ';')
print("Quantidade amostra = ",df_white['quality'].count())
df_white.head()

Quantidade amostra =  4898


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [3]:
ax = df_white['quality'].value_counts().sort_index().plot.bar(
                                    y = [1,2,3,4,5,6,7,8,9,10,11],
                                    figsize=(14,8),
                                    title="Quantidade de vinhos por qualidade"
                                    )
ax.set_xlabel("Qualidade")
ax.set_ylabel("Frequência")

Text(0, 0.5, 'Frequência')

## 2 - Pré-Processamento

In [4]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

### Agrupando Classes - 2 Classes

In [5]:
classes_2 = []
for i in df_white['quality']:
    if i >= 0 and i <= 5:
        classes_2.append('1')
    elif i >= 6 and i <= 10:
        classes_2.append('2')
df_white['classes_2'] = classes_2

### Agrupando Classes - 3 Classes

In [6]:
classes_3 = []
for i in df_white['quality']:
    if i >= 0 and i <= 3:
        classes_3.append('1')
    elif i >= 4 and i <= 6:
        classes_3.append('2')
    elif i >= 7 and i <= 10:
        classes_3.append('3')
df_white['classes_3'] = classes_3  
df_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality classes_2 classes_3  
0      8.8        6         2         2  
1      9.5        6         2         2  
2     10.1        6         2         2  
3      9.9        6         2         2  
4      9.9        6         2         2

### StandardScale
> class sklearn.preprocessing.StandardScaler(**copy**=True, **with_mean**=True, **with_std**=True)

In [22]:
X = df_white.iloc[:,:11]
ss = StandardScaler()
X2 = ss.fit_transform(X)
X2

array([[ 1.72096961e-01, -8.17699008e-02,  2.13280202e-01, ...,
        -1.24692128e+00, -3.49184257e-01, -1.39315246e+00],
       [-6.57501128e-01,  2.15895632e-01,  4.80011213e-02, ...,
         7.40028640e-01,  1.34184656e-03, -8.24275678e-01],
       [ 1.47575110e+00,  1.74519434e-02,  5.43838363e-01, ...,
         4.75101984e-01, -4.36815783e-01, -3.36667007e-01],
       ...,
       [-4.20473102e-01, -3.79435433e-01, -1.19159198e+00, ...,
        -1.31315295e+00, -2.61552731e-01, -9.05543789e-01],
       [-1.60561323e+00,  1.16673788e-01, -2.82557040e-01, ...,
         1.00495530e+00, -9.62604939e-01,  1.85757201e+00],
       [-1.01304317e+00, -6.77100966e-01,  3.78559282e-01, ...,
         4.75101984e-01, -1.48839409e+00,  1.04489089e+00]])

## 3 - Treinamento

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
# Normalmente, em python, o X tem relação com o dataframe gerado e o 'y' com os valores em target
X = df_white.iloc[:,:11]
y = df_white['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, random_state=1)

### Bagging
>class sklearn.ensemble.BaggingClassifier(**base_estimator**=None, **n_estimators**=10, **max_samples**=1.0, **max_features**=1.0, **bootstrap**=True, **bootstrap_features**=False, **oob_score**=False, **warm_start**=False, **n_jobs**=None, **random_state**=None, **verbose**=0)

In [10]:
from sklearn.ensemble import BaggingClassifier

bc = BaggingClassifier()
bc.fit(X_train,y_train)
bc_predict = bc.predict(X_test)

### Decision Tree
> class sklearn.tree.DecisionTreeClassifier(**criterion**='gini', **splitter**='best', **max_depth**=None, **min_samples_split**=2, **min_samples_leaf**=1, **min_weight_fraction_leaf**=0.0, **max_features**=None, **random_state**=None, **max_leaf_nodes**=None, **min_impurity_decrease**=0.0, **min_impurity_split**=None, **class_weight**=None, **presort**='deprecated', **ccp_alpha**=0.0)

In [11]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)
dtc_predict = dtc.predict(X_test)

### Random Forest
> class sklearn.ensemble.RandomForestClassifier(**n_estimators**=100, **criterion**='gini', **max_depth**=None, **min_samples_split**=2, **min_samples_leaf**=1, **min_weight_fraction_leaf**=0.0, **max_features**='auto', **max_leaf_nodes**=None, **min_impurity_decrease**=0.0, **min_impurity_split**=None, **bootstrap**=True, **oob_score**=False, **n_jobs**=None, **random_state**=None, **verbose**=0, **warm_start**=False, **class_weight**=None, **ccp_alpha**=0.0, **max_samples**=None)


In [12]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc.fit(X_train,y_train)
rfc_predict = rfc.predict(X_test)

In [13]:
feature_importantes = pd.DataFrame(rfc.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)
print(feature_importantes)

                      importance
alcohol                 0.114995
density                 0.104174
volatile acidity        0.102449
free sulfur dioxide     0.093194
total sulfur dioxide    0.090330
pH                      0.087341
residual sugar          0.086188
chlorides               0.084432
sulphates               0.080234
citric acid             0.080040
fixed acidity           0.076622


## 4 - Avaliação

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score,f1_score

### Bagging

In [15]:
bc_conf_matrix = confusion_matrix(y_test, bc_predict)
bc_acc_score = accuracy_score(y_test, bc_predict)
print(bc_conf_matrix)
print(bc_acc_score*100)

[[  0   0   1   1   0   0]
 [  0   6  20  10   1   0]
 [  0   9 246 105   8   0]
 [  0   2  90 413  38   1]
 [  0   0  13  96 117   7]
 [  0   0   1  16  11  13]]
64.89795918367346


### Decision Tree

In [16]:
dtc_conf_matrix = confusion_matrix(y_test, dtc_predict)
dtc_acc_score = accuracy_score(y_test, dtc_predict)
print(dtc_conf_matrix)
print(dtc_acc_score*100)

[[  0   0   1   1   0   0   0]
 [  2   8  16   6   5   0   0]
 [  0  16 212 116  22   2   0]
 [  1   7 101 364  61  10   0]
 [  0   1  17  76 123  14   2]
 [  0   1   0  13  12  15   0]
 [  0   0   0   0   0   0   0]]
58.93877551020408


### Random Forest

#### Matriz de Confusão

In [17]:
rfc_conf_matrix = confusion_matrix(y_test, rfc_predict)
rfc_conf_matrix

array([[  0,   0,   1,   1,   0,   0],
       [  0,   7,  20,  10,   0,   0],
       [  0,   4, 237, 124,   3,   0],
       [  0,   0,  72, 445,  27,   0],
       [  0,   0,   5,  98, 129,   1],
       [  0,   0,   1,  14,  12,  14]])

#### Acurácia

In [18]:
rfc_acc_score = accuracy_score(y_test, rfc_predict)
print('Acurácia =',rfc_acc_score*100)


Acurácia = 67.91836734693878


#### Revocação

### Precisão

#### F1-Score

# Reduzindo o número de classes

In [19]:
#novos targets

y2= df_white['classes_2']
y3= df_white['classes_3']
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, train_size = 0.75, random_state=1)
X_train, X_test, y3_train, y3_test = train_test_split(X, y3, train_size = 0.75, random_state=1)

#bagging

bc2 = BaggingClassifier()
bc2.fit(X_train,y2_train)
bc2_predict = bc2.predict(X_test)

bc3 = BaggingClassifier()
bc3.fit(X_train,y3_train)
bc3_predict = bc3.predict(X_test)


#decision tree
dtc2 = DecisionTreeClassifier()
dtc2.fit(X_train,y2_train)
dtc2_predict = dtc2.predict(X_test)

dtc3 = DecisionTreeClassifier()
dtc3.fit(X_train,y3_train)
dtc3_predict = dtc3.predict(X_test)

#random forest
rfc2 = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc2.fit(X_train,y2_train)
rfc2_predict = rfc2.predict(X_test)

rfc3 = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc3.fit(X_train,y3_train)
rfc3_predict = rfc3.predict(X_test)

In [20]:
br = accuracy_score(y_test, bc_predict) * 100
br2 = accuracy_score(y2_test, bc2_predict) * 100
br3 = accuracy_score(y3_test, bc3_predict) * 100


dtr = accuracy_score(y_test, dtc_predict) * 100
dtr2 = accuracy_score(y2_test, dtc2_predict) * 100
dtr3 = accuracy_score(y3_test, dtc3_predict) * 100

rfr = accuracy_score(y_test, rfc_predict) * 100
rfr2 = accuracy_score(y2_test, rfc2_predict) * 100
rfr3 = accuracy_score(y3_test, rfc3_predict) * 100

datavis = {'Bagging': [br,br2,br3], 'Decision Tree':[dtr,dtr2,dtr3], 'Random Forest': [rfr,rfr2,rfr3]}

dataprint = pd.DataFrame(data = datavis)
pd.set_option("display.precision", 2)
dataprint.rename(index={0:'Original', 1: 'Duas Classes', 2: 'Três Classes'}, inplace= True)

dataprint

Bagging  Decision Tree  Random Forest
Original        64.90          58.94          67.92
Duas Classes    82.20          77.39          83.02
Três Classes    84.73          82.20          87.84

## Com Standard Scale

In [23]:
#novos targets

y2= df_white['classes_2']
y3= df_white['classes_3']
X_train, X_test, y2_train, y2_test = train_test_split(X2, y2, train_size = 0.75, random_state=1)
X_train, X_test, y3_train, y3_test = train_test_split(X2, y3, train_size = 0.75, random_state=1)

#bagging

bc2 = BaggingClassifier()
bc2.fit(X_train,y2_train)
bc2_predict = bc2.predict(X_test)

bc3 = BaggingClassifier()
bc3.fit(X_train,y3_train)
bc3_predict = bc3.predict(X_test)


#decision tree
dtc2 = DecisionTreeClassifier()
dtc2.fit(X_train,y2_train)
dtc2_predict = dtc2.predict(X_test)

dtc3 = DecisionTreeClassifier()
dtc3.fit(X_train,y3_train)
dtc3_predict = dtc3.predict(X_test)

#random forest
rfc2 = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc2.fit(X_train,y2_train)
rfc2_predict = rfc2.predict(X_test)

rfc3 = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc3.fit(X_train,y3_train)
rfc3_predict = rfc3.predict(X_test)

In [24]:
br = accuracy_score(y_test, bc_predict) * 100
br2 = accuracy_score(y2_test, bc2_predict) * 100
br3 = accuracy_score(y3_test, bc3_predict) * 100


dtr = accuracy_score(y_test, dtc_predict) * 100
dtr2 = accuracy_score(y2_test, dtc2_predict) * 100
dtr3 = accuracy_score(y3_test, dtc3_predict) * 100

rfr = accuracy_score(y_test, rfc_predict) * 100
rfr2 = accuracy_score(y2_test, rfc2_predict) * 100
rfr3 = accuracy_score(y3_test, rfc3_predict) * 100

datavis = {'Bagging': [br,br2,br3], 'Decision Tree':[dtr,dtr2,dtr3], 'Random Forest': [rfr,rfr2,rfr3]}

dataprint = pd.DataFrame(data = datavis)
pd.set_option("display.precision", 2)
dataprint.rename(index={0:'Original', 1: 'Duas Classes', 2: 'Três Classes'}, inplace= True)

dataprint

Bagging  Decision Tree  Random Forest
Original        64.90          58.94          67.92
Duas Classes    80.49          78.69          82.94
Três Classes    85.88          83.10          88.00