# Modelos Multiplos Preditivos - Cap. 8
## 0 - Bibliotecas importadas

In [1]:
import pandas as pd
import numpy as np

## 1 - Carregando dataset 'Wine Quality'
* Dados numéricos;
* Não houve necessidade de fazer tratamento quanto a falta ou inconsistência nos dados;
* 11 características e target sendo sobre a qualidade do vinho (0-qualidade ruim- até 10-Excelente qualidade-);
* Não está balanceado (há mais vinhos normais do que excelentes ou ruins);

### Vinho Branco

In [2]:
df_white = pd.read_csv('./winequality-white.csv', sep = ';')
print("Quantidade amostra = ",df_white['quality'].count())
df_white.head()

Quantidade amostra =  4898


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [3]:
ax = df_white['quality'].value_counts().sort_index().plot.bar(
                                    y = [1,2,3,4,5,6,7,8,9,10,11],
                                    figsize=(14,8),
                                    title="Quantidade de vinhos por qualidade"
                                    )
ax.set_xlabel("Qualidade")
ax.set_ylabel("Frequência")

Text(0, 0.5, 'Frequência')

## 2 - Pré-Processamento

In [4]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

### Agrupando Classes - 2 Classes

In [5]:
classes_2 = []
for i in df_white['quality']:
    if i >= 0 and i <= 5:
        classes_2.append('1')
    elif i >= 6 and i <= 10:
        classes_2.append('2')
df_white['classes_2'] = classes_2

### Agrupando Classes - 3 Classes

In [6]:
classes_3 = []
for i in df_white['quality']:
    if i >= 0 and i <= 3:
        classes_3.append('1')
    elif i >= 4 and i <= 6:
        classes_3.append('2')
    elif i >= 7 and i <= 10:
        classes_3.append('3')
df_white['classes_3'] = classes_3  
df_white

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0             0.270         0.36           20.70      0.045   
1               6.3             0.300         0.34            1.60      0.049   
2               8.1             0.280         0.40            6.90      0.050   
3               7.2             0.230         0.32            8.50      0.058   
4               7.2             0.230         0.32            8.50      0.058   
5               8.1             0.280         0.40            6.90      0.050   
6               6.2             0.320         0.16            7.00      0.045   
7               7.0             0.270         0.36           20.70      0.045   
8               6.3             0.300         0.34            1.60      0.049   
9               8.1             0.220         0.43            1.50      0.044   
10              8.1             0.270         0.41            1.45      0.033   
11              8.6             0.230         0.40            4.20      0.035   
12              7.9             0.180         0.37            1.20      0.040   
13              6.6             0.160         0.40            1.50      0.044   
14              8.3             0.420         0.62           19.25      0.040   
15              6.6             0.170         0.38            1.50      0.032   
16              6.3             0.480         0.04            1.10      0.046   
17              6.2             0.660         0.48            1.20      0.029   
18              7.4             0.340         0.42            1.10      0.033   
19              6.5             0.310         0.14            7.50      0.044   
20              6.2             0.660         0.48            1.20      0.029   
21              6.4             0.310         0.38            2.90      0.038   
22              6.8             0.260         0.42            1.70      0.049   
23              7.6             0.670         0.14            1.50      0.074   
24              6.6             0.270         0.41            1.30      0.052   
25              7.0             0.250         0.32            9.00      0.046   
26              6.9             0.240         0.35            1.00      0.052   
27              7.0             0.280         0.39            8.70      0.051   
28              7.4             0.270         0.48            1.10      0.047   
29              7.2             0.320         0.36            2.00      0.033   
...             ...               ...          ...             ...        ...   
4868            5.8             0.230         0.31            4.50      0.046   
4869            6.6             0.240         0.33           10.10      0.032   
4870            6.1             0.320         0.28            6.60      0.021   
4871            5.0             0.200         0.40            1.90      0.015   
4872            6.0             0.420         0.41           12.40      0.032   
4873            5.7             0.210         0.32            1.60      0.030   
4874            5.6             0.200         0.36            2.50      0.048   
4875            7.4             0.220         0.26            1.20      0.035   
4876            6.2             0.380         0.42            2.50      0.038   
4877            5.9             0.540         0.00            0.80      0.032   
4878            6.2             0.530         0.02            0.90      0.035   
4879            6.6             0.340         0.40            8.10      0.046   
4880            6.6             0.340         0.40            8.10      0.046   
4881            5.0             0.235         0.27           11.75      0.030   
4882            5.5             0.320         0.13            1.30      0.037   
4883            4.9             0.470         0.17            1.90      0.035   
4884            6.5             0.330         0.38            8.30      0.048   
4885            6.6             0.340

### StandardScale
> class sklearn.preprocessing.StandardScaler(**copy**=True, **with_mean**=True, **with_std**=True)

In [7]:
ss = StandardScaler()
df_white_scaler = ss.fit_transform(df_white.values.reshape(-1,1))
df_white_scaler

/home/ahmoura/ProgramFiles/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/ahmoura/ProgramFiles/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.21894148],
       [-0.39908096],
       [-0.39667196],
       ...,
       [-0.24570812],
       [-0.35277467],
       [-0.35277467]])

## 3 - Treinamento

In [8]:
from sklearn.model_selection import train_test_split

In [89]:
# Normalmente, em python, o X tem relação com o dataframe gerado e o 'y' com os valores em target
X = df_white.iloc[:,:11]
y = df_white['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.75, random_state=1)

### Bagging
>class sklearn.ensemble.BaggingClassifier(**base_estimator**=None, **n_estimators**=10, **max_samples**=1.0, **max_features**=1.0, **bootstrap**=True, **bootstrap_features**=False, **oob_score**=False, **warm_start**=False, **n_jobs**=None, **random_state**=None, **verbose**=0)

In [22]:
from sklearn.ensemble import BaggingClassifier

bc = BaggingClassifier()
bc.fit(X_train,y_train)
bc_predict = bc.predict(X_test)

array([5, 5, 7, ..., 5, 6, 5])

### Decision Tree
> class sklearn.tree.DecisionTreeClassifier(**criterion**='gini', **splitter**='best', **max_depth**=None, **min_samples_split**=2, **min_samples_leaf**=1, **min_weight_fraction_leaf**=0.0, **max_features**=None, **random_state**=None, **max_leaf_nodes**=None, **min_impurity_decrease**=0.0, **min_impurity_split**=None, **class_weight**=None, **presort**='deprecated', **ccp_alpha**=0.0)

In [11]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train,y_train)
dtc_predict = dtc.predict(X_test)

### Random Forest
> class sklearn.ensemble.RandomForestClassifier(**n_estimators**=100, **criterion**='gini', **max_depth**=None, **min_samples_split**=2, **min_samples_leaf**=1, **min_weight_fraction_leaf**=0.0, **max_features**='auto', **max_leaf_nodes**=None, **min_impurity_decrease**=0.0, **min_impurity_split**=None, **bootstrap**=True, **oob_score**=False, **n_jobs**=None, **random_state**=None, **verbose**=0, **warm_start**=False, **class_weight**=None, **ccp_alpha**=0.0, **max_samples**=None)


In [12]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc.fit(X_train,y_train)
rfc_predict = rfc.predict(X_test)

In [13]:
feature_importantes = pd.DataFrame(rfc.feature_importances_,
                                   index = X_train.columns,
                                    columns=['importance']).sort_values('importance', ascending=False)
print(feature_importantes)

                      importance
alcohol                 0.117014
volatile acidity        0.103491
density                 0.102519
free sulfur dioxide     0.094231
total sulfur dioxide    0.089839
pH                      0.086376
residual sugar          0.085605
chlorides               0.083936
citric acid             0.080479
sulphates               0.079972
fixed acidity           0.076538


## 4 - Avaliação

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score,f1_score

### Bagging

In [15]:
bc_conf_matrix = confusion_matrix(y_test, bc_predict)
bc_acc_score = accuracy_score(y_test, bc_predict)
print(bc_conf_matrix)
print(bc_acc_score*100)

[[  0   1   0   1   0   0]
 [  0   6  20   9   2   0]
 [  0   7 237 113  11   0]
 [  0   2 107 389  45   1]
 [  0   0   8  89 132   4]
 [  0   0   0  12  16  13]]
63.42857142857142


### Decision Tree

In [16]:
dtc_conf_matrix = confusion_matrix(y_test, dtc_predict)
dtc_acc_score = accuracy_score(y_test, dtc_predict)
print(dtc_conf_matrix)
print(dtc_acc_score*100)

[[  0   0   0   2   0   0]
 [  1   7  21   5   2   1]
 [  0  17 216 107  22   6]
 [  1   7 107 359  60  10]
 [  0   4  14  82 119  14]
 [  0   0   0  14  10  17]]
58.61224489795919


### Random Forest

#### Matriz de Confusão

In [17]:
rfc_conf_matrix = confusion_matrix(y_test, rfc_predict)
rfc_conf_matrix

array([[  0,   0,   1,   1,   0,   0],
       [  0,   6,  21,  10,   0,   0],
       [  0,   3, 238, 123,   4,   0],
       [  0,   0,  69, 446,  29,   0],
       [  0,   0,   5,  94, 133,   1],
       [  0,   0,   1,  14,  12,  14]])

#### Acurácia

In [18]:
rfc_acc_score = accuracy_score(y_test, rfc_predict)
print('Acurácia =',rfc_acc_score*100)


Acurácia = 68.3265306122449


#### Revocação

### Precisão

#### F1-Score

# Reduzindo o número de classes

In [116]:
#novos targets

y2= df_white['classes_2']
y3= df_white['classes_3']
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, train_size = 0.75, random_state=1)
X_train, X_test, y3_train, y3_test = train_test_split(X, y3, train_size = 0.75, random_state=1)

#bagging

bc2 = BaggingClassifier()
bc2.fit(X_train,y2_train)
bc2_predict = bc2.predict(X_test)

bc3 = BaggingClassifier()
bc3.fit(X_train,y3_train)
bc3_predict = bc3.predict(X_test)


#decision tree
dtc2 = DecisionTreeClassifier()
dtc2.fit(X_train,y2_train)
dtc2_predict = dtc2.predict(X_test)

dtc3 = DecisionTreeClassifier()
dtc3.fit(X_train,y3_train)
dtc3_predict = dtc3.predict(X_test)

#random forest
rfc2 = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc2.fit(X_train,y2_train)
rfc2_predict = rfc2.predict(X_test)

rfc3 = RandomForestClassifier(n_estimators= 1000,
                              max_features= 'auto',     
                              bootstrap = 'TRUE',
                              oob_score = 'TRUE',
                              n_jobs = -1)
rfc3.fit(X_train,y3_train)
rfc3_predict = rfc3.predict(X_test)

/home/ahmoura/ProgramFiles/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [117]:
br = accuracy_score(y_test, bc_predict) * 100
br2 = accuracy_score(y2_test, bc2_predict) * 100
br3 = accuracy_score(y3_test, bc3_predict) * 100


dtr = accuracy_score(y_test, dtc_predict) * 100
dtr2 = accuracy_score(y2_test, dtc2_predict) * 100
dtr3 = accuracy_score(y3_test, dtc3_predict) * 100

rfr = accuracy_score(y_test, rfc_predict) * 100
rfr2 = accuracy_score(y2_test, rfc2_predict) * 100
rfr3 = accuracy_score(y3_test, rfc3_predict) * 100

datavis = {'Bagging': [br,br2,br3], 'Decision Tree':[dtr,dtr2,dtr3], 'Random Forest': [rfr,rfr2,rfr3]}

dataprint = pd.DataFrame(data = datavis)
pd.set_option("display.precision", 2)
dataprint.rename(index={0:'Original', 1: 'Duas Classes', 2: 'Três Classes'}, inplace= True)

dataprint

Bagging  Decision Tree  Random Forest
Original        62.29          58.61          68.33
Duas Classes    81.14          77.96          82.69
Três Classes    85.88          82.69          88.08